# -*- coding: utf-8 -*-
"""fcc_book_recommendation_knn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/freeCodeCamp/boilerplate-book-recommendation-engine/blob/master/fcc_book_recommendation_knn.ipynb
"""

# import libraries (you may add additional imports but you may not have to)
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt

# get data files
!wget https://cdn.freecodecamp.org/project-data/books/book-crossings.zip

!unzip book-crossings.zip

books_filename = 'BX-Books.csv'
ratings_filename = 'BX-Book-Ratings.csv'

# import csv data into dataframes
df_books = pd.read_csv(
    books_filename,
    encoding = "ISO-8859-1",
    sep=";",
    header=0,
    names=['isbn', 'title', 'author'],
    usecols=['isbn', 'title', 'author'],
    dtype={'isbn': 'str', 'title': 'str', 'author': 'str'})

df_ratings = pd.read_csv(
    ratings_filename,
    encoding = "ISO-8859-1",
    sep=";",
    header=0,
    names=['user', 'isbn', 'rating'],
    usecols=['user', 'isbn', 'rating'],
    dtype={'user': 'int32', 'isbn': 'str', 'rating': 'float32'})

# add your code here - consider creating a new cell for each section of code

# --- Filter out users with < 200 ratings and books with < 100 ratings ---
user_counts = df_ratings['user'].value_counts()
valid_users = user_counts[user_counts >= 200].index

book_counts = df_ratings['isbn'].value_counts()
valid_books = book_counts[book_counts >= 100].index

df_ratings_filtered = df_ratings[
    (df_ratings['user'].isin(valid_users)) &
    (df_ratings['isbn'].isin(valid_books))
]

# --- Merge with book titles ---
df = df_ratings_filtered.merge(df_books, on='isbn')

# Drop duplicate (user, title) pairs - some isbns map to the same title
df = df.drop_duplicates(['user', 'title'])

# --- Build book x user pivot table (rows = books, cols = users) ---
book_pivot = df.pivot(index='title', columns='user', values='rating').fillna(0)

# Convert to sparse matrix for memory efficiency
book_sparse = csr_matrix(book_pivot.values)

# --- Fit KNN model using cosine distance ---
model = NearestNeighbors(metric='cosine', algorithm='brute')
model.fit(book_sparse)

# function to return recommended books - this will be tested
def get_recommends(book = ""):
  # locate the row for the given book title
  try:
    book_idx = book_pivot.index.get_loc(book)
  except KeyError:
    return [book, []]

  distances, indices = model.kneighbors(
      book_pivot.iloc[book_idx, :].values.reshape(1, -1),
      n_neighbors=6  # 6 because index 0 will be the book itself
  )

  recommended_books = []
  # iterate from farthest to closest (excluding the book itself at index 0)
  for i in range(len(distances[0]) - 1, 0, -1):
    title = book_pivot.index[indices[0][i]]
    dist = distances[0][i]
    recommended_books.append([title, dist])

  return [book, recommended_books]

books = get_recommends("Where the Heart Is (Oprah's Book Club (Paperback))")
print(books)

def test_book_recommendation():
  test_pass = True
  recommends = get_recommends("Where the Heart Is (Oprah's Book Club (Paperback))")
  if recommends[0] != "Where the Heart Is (Oprah's Book Club (Paperback))":
    test_pass = False
  recommended_books = ["I'll Be Seeing You", 'The Weight of Water', 'The Surgeon', 'I Know This Much Is True']
  recommended_books_dist = [0.8, 0.77, 0.77, 0.77]
  for i in range(2):
    if recommends[1][i][0] not in recommended_books:
      test_pass = False
    if abs(recommends[1][i][1] - recommended_books_dist[i]) >= 0.05:
      test_pass = False
  if test_pass:
    print("You passed the challenge! 🎉🎉🎉🎉🎉")
  else:
    print("You haven't passed yet. Keep trying!")

test_book_recommendation()